rss: atom.xml
fancybox: true
favicon: favicon.png
inverse_sort: true  # Whether to sort all notes inversely
fold: false  # Whether to fold all the notebooks initially
scratch_name: Others  # Notebook name of posts without categories variables
google_analytics: true
search:
 path: search.xml
 field: all
